In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [4]:
df = pd.read_csv('Car_Purchasing_Data.csv')
df

Gender        Age  Annual Salary  Credit Card Debt    Net Worth  \
0         0  41.851720    62812.09301      11609.380910  238961.2505   
1         0  40.870623    66646.89292       9572.957136  530973.9078   
2         1  43.152897    53798.55112      11160.355060  638467.1773   
3         1  58.271369    79370.03798      14426.164850  548599.0524   
4         1  57.313749    59729.15130       5358.712177  560304.0671   
..      ...        ...            ...               ...          ...   
495       0  41.462515    71942.40291       6995.902524  541670.1016   
496       1  37.642000    56039.49793      12301.456790  360419.0988   
497       1  53.943497    68888.77805      10611.606860  764531.3203   
498       1  59.160509    49811.99062      14013.034510  337826.6382   
499       1  46.731152    61370.67766       9391.341628  462946.4924   

     Car Purchase Amount  
0            35321.45877  
1            45115.52566  
2            42925.70921  
3            67422.36313  
4            55915.46248  
..                   ...  
495          48901.44342  
496          31491.41457  
497          64147.28888  
498          45442.15353  
499          45107.22566  

[500 rows x 6 columns]

In [5]:
len(df)

500

In [6]:
df.shape

(500, 6)

In [7]:
df.size

3000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Gender               500 non-null    int64  
 1   Age                  500 non-null    float64
 2   Annual Salary        500 non-null    float64
 3   Credit Card Debt     500 non-null    float64
 4   Net Worth            500 non-null    float64
 5   Car Purchase Amount  500 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 23.6 KB


In [9]:
#Performing MUltiple Linear Regression

X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [10]:
X

Gender        Age  Annual Salary  Credit Card Debt    Net Worth
0         0  41.851720    62812.09301      11609.380910  238961.2505
1         0  40.870623    66646.89292       9572.957136  530973.9078
2         1  43.152897    53798.55112      11160.355060  638467.1773
3         1  58.271369    79370.03798      14426.164850  548599.0524
4         1  57.313749    59729.15130       5358.712177  560304.0671
..      ...        ...            ...               ...          ...
495       0  41.462515    71942.40291       6995.902524  541670.1016
496       1  37.642000    56039.49793      12301.456790  360419.0988
497       1  53.943497    68888.77805      10611.606860  764531.3203
498       1  59.160509    49811.99062      14013.034510  337826.6382
499       1  46.731152    61370.67766       9391.341628  462946.4924

[500 rows x 5 columns]

In [11]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...     
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
len(X_train) , len(y_train)

(350, 350)

In [14]:
len(X_test) , len(y_test)

(150, 150)

In [15]:
X_train

Gender        Age  Annual Salary  Credit Card Debt    Net Worth
5         1  56.824893    68499.85162      14179.472440  428485.3604
116       1  43.031069    69175.19403       6039.594519  325701.4083
45        0  55.275143    70787.27764      10155.340950  853913.8532
16        0  44.742200    63259.87837      11495.549990  370356.2223
462       0  39.141035    66680.27410      10263.148990  556945.8742
..      ...        ...            ...               ...          ...
106       0  41.796014    51075.46118      12416.848450  450402.2932
270       0  35.375156    33422.99683       8570.611562  211168.6293
348       0  45.305941    63561.04525       3730.119720  608019.6308
435       1  57.974293    41409.29390       8211.340920  421318.9764
102       1  30.492353    68289.18229       7357.787011  404457.3099

[350 rows x 5 columns]

In [16]:
y_train

5      56611.99784
116    42408.02625
45     68925.09447
16     41814.72067
462    44430.63323
          ...     
106    34803.82395
270    12536.93842
348    49348.88394
435    42139.64528
102    33640.73697
Name: Car Purchase Amount, Length: 350, dtype: float64

In [17]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [18]:
reg.coef_

array([-5.99401193e-02,  8.41564679e+02,  5.62334352e-01, -2.90660624e-05,
        2.89836840e-02])

In [19]:
reg.intercept_

-42147.25929316858

In [20]:
-5.99401193e-02*1	 + 8.41564679e+02*56.824893+ 5.62334352e-01*68499.85162+ -2.90660624e-05*14179.472440 + 2.89836840e-02*428485.3604 + -42147.25929316858

56612.99541932429

In [21]:
#Training_data Performance


y_train_pred = reg.predict(X_train)
y_train_pred

array([56612.9954996 , 42405.54760383, 68925.74034943, 41813.35176029,
       44431.10711999, 39269.96796049, 67424.30820745, 56562.50572671,
       45113.79446678, 37349.28309601, 49139.07525807, 39607.72351574,
       48515.36454392, 43991.80150333, 34921.39509945, 48052.95055006,
       37161.84813267, 47434.88210007,  9001.51793095, 27589.64957169,
       10091.80387451, 38170.90657229, 59538.6201211 , 42591.98024911,
       30241.69441766, 49050.03801569, 56765.56404033, 39331.28587765,
       53658.01986332, 29757.51531894, 53993.87323184, 50456.14633048,
       63869.85737968, 38707.0704675 , 46013.11332846, 29425.09315133,
       48956.05567373, 43680.35227086, 55126.09944117, 36110.72469181,
       47761.79417663, 55701.42483024, 70597.29015939, 52709.15668229,
       54974.51265591, 31215.0246528 , 45974.97774087, 25973.00354464,
       42355.55928967, 46713.96353216, 27588.712329  , 42383.73695527,
       34137.74363623, 40876.81978467, 55593.40654571, 46188.67543173,
      

In [22]:
Training_data_Performance = pd.DataFrame()
Training_data_Performance = X_train.copy()
Training_data_Performance['Actual_y_train'] = y_train.copy()
Training_data_Performance['y_train_pred'] = y_train_pred


Training_data_Performance

Gender        Age  Annual Salary  Credit Card Debt    Net Worth  \
5         1  56.824893    68499.85162      14179.472440  428485.3604   
116       1  43.031069    69175.19403       6039.594519  325701.4083   
45        0  55.275143    70787.27764      10155.340950  853913.8532   
16        0  44.742200    63259.87837      11495.549990  370356.2223   
462       0  39.141035    66680.27410      10263.148990  556945.8742   
..      ...        ...            ...               ...          ...   
106       0  41.796014    51075.46118      12416.848450  450402.2932   
270       0  35.375156    33422.99683       8570.611562  211168.6293   
348       0  45.305941    63561.04525       3730.119720  608019.6308   
435       1  57.974293    41409.29390       8211.340920  421318.9764   
102       1  30.492353    68289.18229       7357.787011  404457.3099   

     Actual_y_train  y_train_pred  
5       56611.99784  56612.995500  
116     42408.02625  42405.547604  
45      68925.09447  68925.740349  
16      41814.72067  41813.351760  
462     44430.63323  44431.107120  
..              ...           ...  
106     34803.82395  34802.232650  
270     12536.93842  12538.317852  
348     49348.88394  49345.720293  
435     42139.64528  42138.803891  
102     33640.73697  33637.770410  

[350 rows x 7 columns]

In [23]:
Training_data_Performance.index

Index([  5, 116,  45,  16, 462, 357,   3, 218, 405,  60,
       ...
       121, 499,  20, 188,  71, 106, 270, 348, 435, 102],
      dtype='int64', length=350)

In [24]:
c = 0
for i in Training_data_Performance.index:
  c = c + (Training_data_Performance['Actual_y_train'][i] - Training_data_Performance['y_train_pred'][i])**2

print(c / len(Training_data_Performance))

2.239972064726907


In [25]:
from sklearn.metrics import mean_squared_error,r2_score

In [26]:
r2_score(y_train,y_train_pred)

0.9999999812136157

In [27]:
reg.score(X_train,y_train)

0.9999999812136157

In [28]:
mean_squared_error(y_train,y_train_pred)

2.2399720647269072

In [29]:
#Testing_Data_Performance

In [30]:
X_test

Gender        Age  Annual Salary  Credit Card Debt    Net Worth
361       0  36.126918    74420.10254      10274.135580  551344.3365
73        1  47.789729    59139.21080       4630.544424  473845.8546
374       1  57.134576    67752.38329      13851.921220  657178.4135
155       0  50.219573    55381.53225       5088.239017   20000.0000
104       0  48.476396    63975.06090      10614.854490  891439.8761
..      ...        ...            ...               ...          ...
266       1  40.362058    53921.33351       9046.181090  515305.4841
23        1  47.022284    52027.63837      11960.853770  688466.0503
222       0  47.450949    61063.35631      12066.265710  509543.0859
261       0  37.722824    49346.40500       5827.820346  479685.9824
426       1  41.931168    55514.99340       8009.719809  394229.8972

[150 rows x 5 columns]

In [31]:
y_test

361    46082.80993
73     45058.89690
374    63079.84329
155    31837.22537
104    60461.24268
          ...     
266    37076.82508
23     46635.49432
222    46892.26617
261    31249.98803
426    35784.42411
Name: Car Purchase Amount, Length: 150, dtype: float64

In [32]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_test,y_test)

LinearRegression()

In [33]:
reg.coef_

array([7.07092273e-03, 8.41565037e+02, 5.62326909e-01, 2.45823360e-05,
       2.89826264e-02])

In [34]:
reg.intercept_

-42147.01736499498

In [35]:
7.07092273e-03*0	 +  8.41565037e+02*36.126918+ 5.62326909e-01*74420.10254+ 2.45823360e-05*10274.135580 + 2.89826264e-02*551344.3365 + -42147.01736499498

46084.21943194056

In [36]:
y_test_pred = reg.predict(X_test)
y_test_pred

array([46084.21921321, 45060.13579054, 63081.53642833, 31838.3227407 ,
       60460.45067793, 63137.86976301, 52479.8444311 , 54757.38527068,
       52706.95416786, 47869.04393168, 38187.82908085, 56229.68859279,
       44361.69806066, 39002.87498581, 39977.19837178, 55173.31260704,
       48900.72868065, 17584.58579567, 60527.95781016, 49991.22975561,
       41351.95113285, 52785.91528251, 51731.91370956, 38043.18324326,
       41355.40825896, 38241.51718892, 64146.35106392, 47988.14511576,
       22682.30219401, 52242.91580905, 55167.68825319, 45859.27658651,
       41149.00603657, 57430.45008572, 42926.06244964, 39891.99202627,
       61731.79286349, 30840.66512818, 42210.45424676, 40095.90150449,
       57301.6417922 , 60669.98157131, 47443.17620455, 36638.3119922 ,
       53489.10480359, 44433.85233   , 35320.86689545, 42289.79457817,
       52056.96877366, 47241.41546398, 41904.47420799, 32608.19173203,
       38242.58844015, 41767.61389471, 45207.41815019, 48100.15099756,
      

In [37]:
Testing_data_Performance = pd.DataFrame()
Testing_data_Performance = X_test.copy()
Testing_data_Performance['Actual_y_test'] = y_test.copy()
Testing_data_Performance['y_test_pred'] = y_test_pred


Testing_data_Performance

Gender        Age  Annual Salary  Credit Card Debt    Net Worth  \
361       0  36.126918    74420.10254      10274.135580  551344.3365   
73        1  47.789729    59139.21080       4630.544424  473845.8546   
374       1  57.134576    67752.38329      13851.921220  657178.4135   
155       0  50.219573    55381.53225       5088.239017   20000.0000   
104       0  48.476396    63975.06090      10614.854490  891439.8761   
..      ...        ...            ...               ...          ...   
266       1  40.362058    53921.33351       9046.181090  515305.4841   
23        1  47.022284    52027.63837      11960.853770  688466.0503   
222       0  47.450949    61063.35631      12066.265710  509543.0859   
261       0  37.722824    49346.40500       5827.820346  479685.9824   
426       1  41.931168    55514.99340       8009.719809  394229.8972   

     Actual_y_test   y_test_pred  
361    46082.80993  46084.219213  
73     45058.89690  45060.135791  
374    63079.84329  63081.536428  
155    31837.22537  31838.322741  
104    60461.24268  60460.450678  
..             ...           ...  
266    37076.82508  37076.832381  
23     46635.49432  46635.689540  
222    46892.26617  46891.804378  
261    31249.98803  31250.706294  
426    35784.42411  35784.383872  

[150 rows x 7 columns]

In [38]:
Testing_data_Performance.index

Index([361,  73, 374, 155, 104, 394, 377, 124,  68, 450,
       ...
        66, 208, 479,  94, 253, 266,  23, 222, 261, 426],
      dtype='int64', length=150)

In [39]:
d = 0
for i in Testing_data_Performance.index:
  d = d + (Testing_data_Performance['Actual_y_test'][i] - Testing_data_Performance['y_test_pred'][i])**2

print(d / len(Testing_data_Performance))

1.9590174036375834


In [40]:
from sklearn.metrics import mean_squared_error,r2_score
r2_score(y_test,y_test_pred)

0.9999999816406447

In [41]:
reg.score(X_test,y_test)

0.9999999816406447

In [42]:
mean_squared_error(y_test,y_test_pred)

1.959017403637584

In [43]:
import numpy as np
import pandas as pd
import sklearn
import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
class TRAINING:
    def __init__(self,location):
        try:
            self.df = pd.read_csv(location)
            self.X = self.df.iloc[: , :-1] # independent
            self.y = self.df.iloc[: , -1] # dependent
            self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(self.X,self.y,test_size=0.3,random_state=42)
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def data_training(self):
        try:
            self.reg = LinearRegression()
            self.reg.fit(self.X_train,self.y_train) # trainnig
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def train_performance(self):
        try:
            self.y_train_pred = self.reg.predict(self.X_train)
            print(f' Train Accuracy : -> {r2_score(self.y_train,self.y_train_pred)}')
            print(f'Train Loss : {mean_squared_error(self.y_train,self.y_train_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def testing(self):
        try:
            self.y_test_pred = self.reg.predict(self.X_test)
            print(f' Test Accuracy : -> {r2_score(self.y_test, self.y_test_pred)}')
            print(f'Test Loss : {mean_squared_error(self.y_test,self.y_test_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

if __name__ == "__main__":
    try:
        obj = TRAINING('Car_Purchasing_Data.csv') # constructor will be called
        obj.data_training()
        obj.train_performance()
        obj.testing()
    except Exception as e:
        error_type,error_msg,err_line = sys.exc_info()
        print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

 Train Accuracy : -> 0.9999999812136157
Train Loss : 2.2399720647269072
 Test Accuracy : -> 0.9999999808814803
Test Loss : 2.0400233206749734
